### PR TITLE
Update QrScanner.tsx

### LINKED ISSUE #1240: Enhance QR code scanner for Nova wallet compatibility

### PR DESCRIPTION
**Pull request by AMIRKHANEF**
Close #1240 

## Summary by CodeRabbit

- **New Features**
	- Enhanced QR scanner to support NOVA WALLET QR codes, automatically formatting and setting addresses when detected.

### CODE REVIEW

**Comment by Nick-1979** [comment]
cant import from nova, still get "Invalid QR code."

**Comment by AMIRKHANEF** [comment]
@Nick-1979 how do you try to add watch only account from account?

**Comment by Nick-1979** [comment]
I just tried to attach a QR-attached account from nova

**Comment by Nick-1979** [comment]
@AMIRKHANEF  have u tried to add an account from Vault as watch only?

**Comment by AMIRKHANEF** [comment]
Solved.

**Pull request merged**
